// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: iex.proto

package iex

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StockQuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *StockQuoteRequest) Reset() {
	*x = StockQuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockQuoteRequest) ProtoMessage() {}

func (x *StockQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockQuoteRequest.ProtoReflect.Descriptor instead.
func (*StockQuoteRequest) Descriptor() ([]byte, []int) {
	return file_iex_proto_rawDescGZIP(), []int{0}
}

func (x *StockQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type StockQuoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price  float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *StockQuoteResponse) Reset() {
	*x = StockQuoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockQuoteResponse) ProtoMessage() {}

func (x *StockQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockQuoteResponse.ProtoReflect.Descriptor instead.
func (*StockQuoteResponse) Descriptor() ([]byte, []int) {
	return file_iex_proto_rawDescGZIP(), []int{1}
}

func (x *StockQuoteResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockQuoteResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type StockQuoteRequestBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbols []*StockQuoteRequest `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
}

func (x *StockQuoteRequestBatch) Reset() {
	*x = StockQuoteRequestBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iex_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockQuoteRequestBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockQuoteRequestBatch) ProtoMessage() {}

func (x *StockQuoteRequestBatch) ProtoReflect() protoreflect.Message {
	mi := &file_iex_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockQuoteRequestBatch.ProtoReflect.Descriptor instead.
func (*StockQuoteRequestBatch) Descriptor() ([]byte, []int) {
	return file_iex_proto_rawDescGZIP(), []int{2}
}

func (x *StockQuoteRequestBatch) GetSymbols() []*StockQuoteRequest {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type StockQuoteResponseBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quotes []*StockQuoteResponse `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
}

func (x *StockQuoteResponseBatch) Reset() {
	*x = StockQuoteResponseBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iex_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockQuoteResponseBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockQuoteResponseBatch) ProtoMessage() {}

func (x *StockQuoteResponseBatch) ProtoReflect() protoreflect.Message {
	mi := &file_iex_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockQuoteResponseBatch.ProtoReflect.Descriptor instead.
func (*StockQuoteResponseBatch) Descriptor() ([]byte, []int) {
	return file_iex_proto_rawDescGZIP(), []int{3}
}

func (x *StockQuoteResponseBatch) GetQuotes() []*StockQuoteResponse {
	if x != nil {
		return x.Quotes
	}
	return nil
}

var File_iex_proto protoreflect.FileDescriptor

var file_iex_proto_rawDesc = []byte{
	0x0a, 0x09, 0x69, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x65, 0x78,
	0x22, 0x2b, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x42, 0x0a,
	0x12, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x22, 0x4a, 0x0a, 0x16, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x30, 0x0a, 0x07, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69,
	0x65, 0x78, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x22, 0x4a, 0x0a,
	0x17, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x2f, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x65, 0x78, 0x2e, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x06, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x73, 0x32, 0xac, 0x01, 0x0a, 0x03, 0x49, 0x65,
	0x78, 0x12, 0x4a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x69, 0x65, 0x78,
	0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x69, 0x65, 0x78, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75,
	0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x2e, 0x69, 0x65,
	0x78, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x1c, 0x2e, 0x69, 0x65, 0x78, 0x2e, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x37, 0x64, 0x39, 0x63, 0x63, 0x32, 0x34, 0x33, 0x31,
	0x39, 0x65, 0x65, 0x64, 0x36, 0x33, 0x38, 0x31, 0x65, 0x31, 0x37, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x65, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iex_proto_rawDescOnce sync.Once
	file_iex_proto_rawDescData = file_iex_proto_rawDesc
)

func file_iex_proto_rawDescGZIP() []byte {
	file_iex_proto_rawDescOnce.Do(func() {
		file_iex_proto_rawDescData = protoimpl.X.CompressGZIP(file_iex_proto_rawDescData)
	})
	return file_iex_proto_rawDescData
}

var file_iex_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_iex_proto_goTypes = []interface{}{
	(*StockQuoteRequest)(nil),       // 0: iex.StockQuoteRequest
	(*StockQuoteResponse)(nil),      // 1: iex.StockQuoteResponse
	(*StockQuoteRequestBatch)(nil),  // 2: iex.StockQuoteRequestBatch
	(*StockQuoteResponseBatch)(nil), // 3: iex.StockQuoteResponseBatch
}
var file_iex_proto_depIdxs = []int32{
	0, // 0: iex.StockQuoteRequestBatch.symbols:type_name -> iex.StockQuoteRequest
	1, // 1: iex.StockQuoteResponseBatch.quotes:type_name -> iex.StockQuoteResponse
	0, // 2: iex.Iex.GetRealTimeStockQuote:input_type -> iex.StockQuoteRequest
	2, // 3: iex.Iex.GetRealTimeStockQuoteBatch:input_type -> iex.StockQuoteRequestBatch
	1, // 4: iex.Iex.GetRealTimeStockQuote:output_type -> iex.StockQuoteResponse
	3, // 5: iex.Iex.GetRealTimeStockQuoteBatch:output_type -> iex.StockQuoteResponseBatch
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_iex_proto_init() }
func file_iex_proto_init() {
	if File_iex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_iex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockQuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockQuoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iex_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockQuoteRequestBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iex_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockQuoteResponseBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iex_proto_goTypes,
		DependencyIndexes: file_iex_proto_depIdxs,
		MessageInfos:      file_iex_proto_msgTypes,
	}.Build()
	File_iex_proto = out.File
	file_iex_proto_rawDesc = nil
	file_iex_proto_goTypes = nil
	file_iex_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IexClient is the client API for Iex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IexClient interface {
	GetRealTimeStockQuote(ctx context.Context, in *StockQuoteRequest, opts ...grpc.CallOption) (*StockQuoteResponse, error)
	GetRealTimeStockQuoteBatch(ctx context.Context, in *StockQuoteRequestBatch, opts ...grpc.CallOption) (*StockQuoteResponseBatch, error)
}

type iexClient struct {
	cc grpc.ClientConnInterface
}

func NewIexClient(cc grpc.ClientConnInterface) IexClient {
	return &iexClient{cc}
}

func (c *iexClient) GetRealTimeStockQuote(ctx context.Context, in *StockQuoteRequest, opts ...grpc.CallOption) (*StockQuoteResponse, error) {
	out := new(StockQuoteResponse)
	err := c.cc.Invoke(ctx, "/iex.Iex/GetRealTimeStockQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iexClient) GetRealTimeStockQuoteBatch(ctx context.Context, in *StockQuoteRequestBatch, opts ...grpc.CallOption) (*StockQuoteResponseBatch, error) {
	out := new(StockQuoteResponseBatch)
	err := c.cc.Invoke(ctx, "/iex.Iex/GetRealTimeStockQuoteBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IexServer is the server API for Iex service.
type IexServer interface {
	GetRealTimeStockQuote(context.Context, *StockQuoteRequest) (*StockQuoteResponse, error)
	GetRealTimeStockQuoteBatch(context.Context, *StockQuoteRequestBatch) (*StockQuoteResponseBatch, error)
}

// UnimplementedIexServer can be embedded to have forward compatible implementations.
type UnimplementedIexServer struct {
}

func (*UnimplementedIexServer) GetRealTimeStockQuote(context.Context, *StockQuoteRequest) (*StockQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealTimeStockQuote not implemented")
}
func (*UnimplementedIexServer) GetRealTimeStockQuoteBatch(context.Context, *StockQuoteRequestBatch) (*StockQuoteResponseBatch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRealTimeStockQuoteBatch not implemented")
}

func RegisterIexServer(s *grpc.Server, srv IexServer) {
	s.RegisterService(&_Iex_serviceDesc, srv)
}

func _Iex_GetRealTimeStockQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IexServer).GetRealTimeStockQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iex.Iex/GetRealTimeStockQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IexServer).GetRealTimeStockQuote(ctx, req.(*StockQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Iex_GetRealTimeStockQuoteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockQuoteRequestBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IexServer).GetRealTimeStockQuoteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iex.Iex/GetRealTimeStockQuoteBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IexServer).GetRealTimeStockQuoteBatch(ctx, req.(*StockQuoteRequestBatch))
	}
	return interceptor(ctx, in, info, handler)
}

var _Iex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iex.Iex",
	HandlerType: (*IexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRealTimeStockQuote",
			Handler:    _Iex_GetRealTimeStockQuote_Handler,
		},
		{
			MethodName: "GetRealTimeStockQuoteBatch",
			Handler:    _Iex_GetRealTimeStockQuoteBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iex.proto",
}
